# This file is part of the Home Assistant role.
#
# Copyright (c) 2015-2017 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under MIT. All rights reserved.
#
---
- name: open port for home assistant
  firewalld: port={{ ha_port }}/tcp
             permanent=true
             state=enabled
             immediate=yes

- name: open port for cockpit
  firewalld: port=9090/tcp
             permanent=true
             state=enabled
             immediate=yes

- name: open port for mqtt
  firewalld: port=1883/tcp
             permanent=true
             state=enabled
             immediate=yes

