# This file is part of the Home Assistant role.
#
# Copyright (c) 2015-2020 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under Apache 2.0. All rights reserved.
#
---
- name: install required python modules (pre-install)
  pip:
    name: "{{ item }}"
    extra_args: "--upgrade"
    virtualenv: "{{ ha_conf_dir }}"
  with_items:
    - colorlog

- name: install defined version of Home Assistant
  pip:
    name: homeassistant
    version: "{{ ha_version }}"
    virtualenv: "{{ ha_conf_dir }}"
  when: ha_version is defined

- name: install latest version of Home Assistant
  pip:
    name: homeassistant
    extra_args: "--upgrade"
    virtualenv: "{{ ha_conf_dir }}"
  when: ha_version is undefined
